apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-x
  namespace: argocd
spec:
  project : default
  source:   ## The source of the application, which can be a Git repository, Helm chart, Kustomize directory, or other supported sources.
    repoURL: https://github.com/zmanjith/etb169-sandbox-plaform.git
    targetRevision: master ## From where we are tking the yaml or manifest files. It can be a branch, tag, or commit.
    path: app/demo-sandbox-chart/nettest-pod.yaml
  destination:  ## The destination cluster and namespace where the application will be deployed.
    server: https://kubernetes.default.svc
    namespace: tenant-x
  syncPolicy:  ## The sync policy defines how the application is synchronized with the source.
    automated:  ## If set, the application will be automatically synchronized with the source.
      prune: true  ## If set, resources that are no longer defined in the source will be deleted.
      selfHeal: true  ## If set, the application will automatically revert any changes made to the resources in the cluster.
    syncOptions:  ## Additional options for synchronization.
      - CreateNamespace=true  ## If set, the namespace will be created if it does not exist.