apiVersion: v1
kind: Pod
metadata:
  name: nettest
  namespace: tenant-a
spec:
  restartPolicy: Never
  containers:
    - name: nettest
      image: busybox:1.36
      command:
        [
          "wget",
          "-qO-",
          "--timeout=3",
          "http://tenant-b-service.tenant-b.svc.cluster.local:80",
        ]
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
