apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-sandboxes
  namespace: argocd
spec:
  generators:   ## For automatically generating the Applications using parameters. Here "git genearator" used
  - git:
      repoURL: https://github.com/zmanjith/etb169-sandbox-plaform.git
      revision : add-tenant
      files:
       - path: "app/tenants/*.yaml"
  template:
    metadata:
      name: '{{tenantName}}'
    spec:
      project: default  # This is the ArgoCD project where the application will be created. 
                      # the built-in default AppProject ships wide open (* server, * namespace) — it imposes zero restriction.
                      # You can create your own AppProject to restrict the access to specific clusters and namespaces.
                      # Since its default project, it can deploy to any cluster and namespace. 
      source:   ## Source where we trigger the application to be generated and deployed to destination.
        repoURL: https://github.com/zmanjith/etb169-sandbox-plaform.git
        targetRevision: HEAD
        path: app/demo-sandbox-chart
        helm:
         parameters:
          - name: tenantName
            value: '{{tenantName}}'
          - name: tenantHost
            value: '{{tenantHost}}'
          - name: image.tag
            value: '{{imageTag}}'
          - name: dbPassword
            value: '{{dbPassword}}'
      destination: ## Destination where we are going to deploy the application. Here its to the Kubernetes Cluster.
        server: https://kubernetes.default.svc
        namespace: '{{tenantName}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
