apiVersion: batch/v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-deb-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_HOST: {{.Values.db.host }}
  DB_PORT: {{.Values.db.port }}
  DB_NAME: {{.Values.db.name }}
  DB_SCHEMA: {{.Values.tenantName }}
  DB_USER: {{.Values.tenantName }}_app
  DB_PASSWORD: {{ .Values.dbPassword }}
  