apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.tenantName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    tenant: {{ .Values.tenantName  }}
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tenant: {{ .Values.tenantName  }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 8 }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
              
      serviceAccountName: {{ include "demo-sandbox-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
